apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth-prod

bases:
  - ../../base

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml
  - hpa.yaml

patches:
  - path: replicas-patch.yaml

images:
  - name: auth-service
    newTag: "1.0.0"   # pinned release tag in prod

commonLabels:
  environment: prod
