apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth-uat
data:
  SPRING_PROFILES_ACTIVE: "uat"
  DB_URL: "jdbc:postgresql://postgres-uat:5432/authdb_uat"
  CORS_ALLOWED_ORIGINS: "https://uat.example.com"
